export const totalChildren = [
  {
    id: 1,
    name: "Yesuf Mohammed",
    img: "https://cdn.givecloud.co/s/files/2/0000/0908/sponsorships/img-1877_300x_cropped_center.jpg",
    age: 10,
    country: "Ethiopia",
    subject: "Science",
    activity: "Playing soccer",
    circumstances:
      "Yesuf lives with his parents and 3 siblings in Addis Ababa. Sadly, his mother suffers from poor health and is unable to work. His father's meager earnings alone are not enough to meet the family's needs and they cannot afford to send Yesuf to school.",
    food: "Potato",
    grade: 3,
    profession: "Pilot",
  },
  {
    id: 2,
    name: "Kedir Bori",
    img: "https://cdn.givecloud.co/s/files/2/0000/0908/sponsorships/img-3149_300x_cropped_center.jpg",
    age: 9,
    country: "Ethiopia",
    subject: "Science",
    activity: "Playing soccer",
    circumstances:
      "Kedir lives with his parents and siblings in a village in the Oromia region of Ethiopia. His parents both work hard as daily laborers, but their meager earnings are unfortunately not enough to meet the family's needs. Without support, they cannot afford to pay school fees and Kedir's education is at risk.",
    food: "Noodles",
    grade: 1,
    profession: "Teacher",
  },
  {
    id: 3,
    name: "Zerihun Wenjelo",
    img: "https://cdn.givecloud.co/s/files/2/0000/0908/sponsorships/img-3714_300x_cropped_center.jpg",
    age: 10,
    country: "Ethiopia",
    subject: "Afan Oromo (Regional Language)",
    activity: "Playing soccer",
    circumstances:
      "Zerihun is an active boy who lives with his family in the Oromia region of Ethiopia. Zerihun's parents struggle to find permanent jobs, and their earnings as daily laborers are not enough to meet the needs of their large family. Without support, they cannot afford to pay Zerihun's school fees and materials, putting this bright boy's education at risk.",
    food: "Pasta",
    grade: 2,
    profession: "Police Officer",
  },
  {
    id: 4,
    name: "Bayissa Sefissa",
    img: "https://cdn.givecloud.co/s/files/2/0000/0908/sponsorships/img-4182_300x_cropped_center.jpg",
    age: 9,
    country: "Ethiopia",
    subject: "Afan Oromo (Regional Language)",
    activity: "running",
    circumstances:
      "Bayissa lives with his big family in the Oromia region of Ethiopia. His parents work hard doing daily labor jobs to provide for the family, but without a steady income it is difficult to make ends meet. Unable to afford school fees, Bayissa's education is at risk. Your support will empower him to stay in school and continue pursuing his big dreams.",
    food: "Meat",
    grade: 2,
    profession: "Doctor",
  },
  {
    id: 5,
    name: "Riyad Ahmed",
    img: "https://cdn.givecloud.co/s/files/2/0000/0908/sponsorships/img-6089_300x_cropped_center.jpg",
    age: 8,
    country: "Ethiopia",
    subject: "Afan Oromo (Regional Language)",
    activity: "Playing soccer",
    circumstances:
      "Riyad lives with his family in a village in the Oromia region. Sadly, his family was displaced from their home in another part of Ethiopia and his parents are struggling to find permanent work. Their earnings from doing daily labor jobs are not enough to meet the family's needs and they cannot afford school fees. Without support, this sweet boy's education is at risk.",
    food: "Oranges",
    grade: 1,
    profession: "Doctor",
  },
  {
    id: 6,
    name: "Naol Gezahegne",
    img: "https://cdn.givecloud.co/s/files/2/0000/0908/sponsorships/img-4205_300x_cropped_center.jpg",
    age: 10,
    country: "Ethiopia",
    subject: "Science",
    activity: "Playing soccer",
    circumstances:
      "Naol is a sweet boy who lives with his parents and 3 siblings in a village in the Oromia region. Unfortunately, his parents' earnings are meager and inconsistent, making it difficult to meet the family's needs. Without support, they cannot afford school fees, putting Naol's education at risk.",
    food: "Eggs",
    grade: 3,
    profession: "Doctor",
  },
  {
    id: 7,
    name: "Minassie Mengesha",
    img: "https://cdn.givecloud.co/s/files/2/0000/0908/sponsorships/img-6809_300x_cropped_center.jpg",
    age: 11,
    country: "Ethiopia",
    subject: "Art",
    activity: "Game",
    circumstances:
      "Minassie lives with his mother and siblings in a vulnerable community of Addis Ababa. His father lives away from the family and his parents struggle to provide for the family. Although Minassie's parents works hard as a daily laborer, their earnings are not enough to meet the family's needs and they cannot afford to pay school fees. Without support, Minassie's education is at risk. ",
    food: "Misir",
    grade: 6,
    profession: "Artisit",
  },
  {
    id: 8,
    name: "Yisakor Tamirat",
    img: "https://cdn.givecloud.co/s/files/2/0000/0908/sponsorships/img-6727_300x_cropped_center.jpg",
    age: 12,
    country: "Ethiopia",
    subject: "Environmental Science",
    activity: "Football",
    circumstances:
      "Yisakor lives with his parents and sibling in a vulnerable community of Addis Ababa. Due to their low income, his parents struggle to provide for the family. Although Yisakor's parents works hard as a daily laborer, their earnings are not enough to meet the family's needs and they cannot afford to pay for school fees. Without support, Yisakor's education is at risk.",
    food: "Misir",
    grade: 2,
    profession: "Pilot",
  },
  {
    id: 9,
    name: "Melkamu Tesfaye",
    img: "https://cdn.givecloud.co/s/files/2/0000/0908/sponsorships/img-6858_300x_cropped_center.jpg",
    age: 9,
    country: "Ethiopia",
    subject: "Science",
    activity: "Playing Soccer",
    circumstances:
      "Melkamu is a bright boy who lives with his mother in an impoverished community of Addis Ababa. His father disappeared when he was young, and Melkamu's mother does her best to provide for the family on her own. However, without a permanent income, Melkamu's mother struggles to meet the needs of the family and cannot afford school fees. Your support will empower Melkamu to stay in school and pursuing his big dreams!",
    food: "Rice",
    grade: 1,
    profession: "Police",
  },
  {
    id: 10,
    name: "Yehualashet Tilahun",
    img: "https://cdn.givecloud.co/s/files/2/0000/0908/sponsorships/img-6926_300x_cropped_center.jpg",
    age: 9,
    country: "Ethiopia",
    subject: "Amharic",
    activity: "Hide & Seek",
    circumstances:
      "Yehualashet lives with his mother and three siblings in a vulnerable community of Addis Ababa. His mother struggles to provide for the family on her own as a daily laborer. Yehualashet's mother earning is not enough to meet the family's needs and she cannot afford to pay for his school fees. Without support, Yehualashet's education is at risk.",
    food: "Rice",
    grade: 2,
    profession: "Driver",
  },
  {
    id: 11,
    name: "Abel Andualem",
    img: "https://cdn.givecloud.co/s/files/2/0000/0908/sponsorships/img-7083_300x_cropped_center.jpg",
    age: 12,
    country: "Ethiopia",
    subject: "Science",
    activity: "Football",
    circumstances:
      "Abel is a bright boy who lives with his parents and siblings in a vulnerable community of Addis Ababa. His mother is unemployed, and his father struggles to provide for the family on his own. Although Abel's father works hard as a daily laborer, his earnings are not enough to meet the family's needs and he cannot afford to pay for school fees. Without support, Abel's education is at risk.",
    food: "Spaghetti",
    grade: 6,
    profession: "Soccer Player",
  },
  {
    id: 12,
    name: "Yeabsira Getaneh",
    img: "https://cdn.givecloud.co/s/files/2/0000/0908/sponsorships/img-7160_300x_cropped_center.jpg",
    age: 12,
    country: "Ethiopia",
    subject: "Mathematics",
    activity: "Hide & Seek",
    circumstances:
      "Yeabsira is a bright girl who lives with her mother in a vulnerable community of Addis Ababa. She is raised by a single mother and her mother struggles to provide for the family on her own. Although Yabsira's mother works hard as a daily laborer, her earnings are not enough to meet the family's needs and she cannot afford to pay school fees. Without support, Yabsira's education is at risk",
    food: "Spaghetti",
    grade: 6,
    profession: "Pilot",
  },
  {
    id: 13,
    name: "Salahadin Abdurazak",
    img: "https://cdn.givecloud.co/s/files/2/0000/0908/sponsorships/img-6767_300x_cropped_center.jpg",
    age: 9,
    country: "Ethiopia",
    subject: "Amharic",
    activity: "Playing Soccer",
    circumstances:
      "Salahdin is a bright little boy who lives with his parents and two special needs siblings in an impoverished neighborhood of Addis Ababa. Sadly, his parents struggle to meet the needs of the family without a permanent job. Due to their low income as daily laborers, Salahdin's parents cannot afford to send him to school. Your support will empower Salahdin to stay in school and pursuing big dreams!",
    food: "Pasta",
    grade: 3,
    profession: "Teacher",
  },
  {
    id: 14,
    name: "Yohannes Ewnetagnaw",
    img: "https://cdn.givecloud.co/s/files/2/0000/0908/sponsorships/img-2276_300x_cropped_center.jpg",
    age: 9,
    country: "Ethiopia",
    subject: "Amharic",
    activity: "Playing Soccer",
    circumstances:
      "Yohannes is a bright little boy who lives with his mother in an impoverished neighborhood of Addis Ababa. However, without a permanent income, Yohannes's mother struggles to meet the needs of the family as a daily laborer. Due to her low income, she cannot afford to send him to school. Your support will empower Yohannes to stay in school and pursuing big dreams!",
    food: "Cake",
    grade: 3,
    profession: "Pilot",
  },
  {
    id: 15,
    name: "Biruk Demelash",
    img: "https://cdn.givecloud.co/s/files/2/0000/0908/sponsorships/img-2280_300x_cropped_center.jpg",
    age: 11,
    country: "Ethiopia",
    subject: "Mathematics",
    activity: "Playing Soccer",
    circumstances:
      "Biruk is a bright little boy who lives with his single mother and two siblings in an impoverished neighborhood of Addis Ababa. Sadly, his parents are separated and without a permanent income, Biruk's mother struggles to meet the needs of the family by herself as a daily laborer. Due to her low income, she cannot afford to send him to school. Your support will empower Biruk to stay in school and pursuing big dreams!",
    food: "Pasta",
    grade: 3,
    profession: "Doctor",
  },
  {
    id: 16,
    name: "Yohannes Yibeltal",
    img: "https://cdn.givecloud.co/s/files/2/0000/0908/sponsorships/img-2304_300x_cropped_center.jpg",
    age: 7,
    country: "Ethiopia",
    subject: "Mathematics",
    activity: "Playing Soccer",
    circumstances:
      "Yohannes is a bright little boy who lives with his single mother in an impoverished neighborhood of Addis Ababa. Sadly, his father disappeared and without a permanent income, Yohannes's mother struggles to meet the needs of the family by herself as a daily laborer. Due to her low income, she cannot afford to send him to school. Your support will empower Yohannes to stay in school and pursuing big dreams!",
    food: "Rice",
    grade: "Kindergarten",
    profession: "Doctor",
  },
  {
    id: 17,
    name: "Eyob Abriham",
    img: "https://cdn.givecloud.co/s/files/2/0000/0908/sponsorships/eyob-abriham_300x_cropped_center.jpg",
    age: 5,
    country: "Ethiopia",
    subject: "Science",
    activity: "Sewing",
    circumstances:
      "Eyob is a bright little boy who lives with his parents and three siblings in an impoverished community in Addis Ababa. Although Eyob's parents work hard as daily laborers, their earnings are not enough to meet the family's needs and they cannot afford to pay his school fees. Without support, Eyob's education is at risk.",
    food: "Spaghetti",
    grade: 1,
    profession: "Doctor",
  },
  {
    id: 18,
    name: "Mikias Getu",
    img: "https://cdn.givecloud.co/s/files/2/0000/0908/sponsorships/microsoftteams-image-10_300x_cropped_center.png",
    age: 12,
    country: "Ethiopia",
    subject: "English",
    activity: "Playing Soccer",
    circumstances:
      "Mikias is a bright little boy who lives with his parents and a sibling in an impoverished neighborhood of Addis Ababa. His father is blind, and he does not work. Sadly, Mikias's mother has a Kidney illness, and she has hard time working as daily laborers. Due to their law earnings, Mikias's parents cannot meet the family's needs and they cannot afford to pay his school fees. Without support, Mikias's education is at risk.",
    food: "Fifir (Traditional Food)",
    grade: 4,
    profession: "Soccer Player",
  },
  {
    id: 19,
    name: "Desalegne Anegagregn",
    img: "https://cdn.givecloud.co/s/files/2/0000/0908/sponsorships/microsoftteams-image-15_300x_cropped_center.png",
    age: 5,
    country: "Ethiopia",
    subject: "English Alphabet",
    activity: "Watching TV",
    circumstances:
      "Desalegne is a bright little boy who lives with his parents and a sibling in an impoverished neighborhood of Addis Ababa. Although Desalegne's parents work hard as daily laborers, their earnings are not enough to meet the family's needs and they cannot afford to pay his school fees. Without support, Desalegne's education is at risk.",
    food: "Cake",
    grade: "Kindergarten",
    profession: "Too early to decide.",
  },
  {
    id: 20,
    name: "Nahom Tibebu",
    img: "https://cdn.givecloud.co/s/files/2/0000/0908/sponsorships/microsoftteams-image-13_300x_cropped_center.png",
    age: 8,
    country: "Ethiopia",
    subject: "Mathematics",
    activity: "Hide and seek",
    circumstances:
      "Nahom is a sweet little boy who lives with his mother and a sibling in an impoverished neighborhood of Addis Ababa. Sadly, Nahom's father has passed away and his mother's income is inconsistent even though she works hard as daily laborer. Nahom's mother earnings are not enough to meet the family's needs and she cannot afford to pay his school fees. Without support, Nahom's education is at risk.",
    food: "Shiro (Traditional Food)Cake",
    grade: 2 ,
    profession: "Doctor",
  },
  {
    id: 21,
    name: "Yafet Habtamu",
    img: "https://cdn.givecloud.co/s/files/2/0000/0908/sponsorships/microsoftteams-image-17_300x_cropped_center.png",
    age: 5,
    country: "Ethiopia",
    subject: "Mathematics",
    activity: "Slides",
    circumstances:
      "Yafet is a bright little boy who lives with his father and grandmother in an impoverished neighborhood of Addis Ababa. Sadly, his mother abandoned him and disappeared at a young age. Although Yafet's grandmother work hard as domestic worker, her inconsistent earnings are not enough to meet the family's needs and she cannot afford to pay his school fees. Without support, Yafet's education is at risk.",
    food: "Shiro (Traditional Food)Cake",
    grade: "Kindergarten" ,
    profession: "Pilot",
  },
  {
    id: 22,
    name: "Habtamu Negash",
    img: "https://cdn.givecloud.co/s/files/2/0000/0908/sponsorships/habtamu-shambel_300x_cropped_center.jpg",
    age: 8,
    country: "Ethiopia",
    subject: "Afan Oromo (Regional Language)",
    activity: "Playing Soccer",
    circumstances:
      "Habtamu is a bright boy who lives with his mother and three siblings in an impoverished neighborhood of Addis Ababa. Sadly, his father has passed away and although Habtamu's mother work hard as a daily laborer, her earnings are not enough to meet the family's needs and she cannot afford to pay his school fees. Without support, Habtamu's education is at risk.",
    food: "Enjera (Traditional Food)",
    grade: 3 ,
    profession: "Policeman",
  },
  {
    id: 23,
    name: "Yoseph Getachew",
    img: "https://cdn.givecloud.co/s/files/2/0000/0908/sponsorships/microsoftteams-image-18_300x_cropped_center.png",
    age: 9,
    country: "Ethiopia",
    subject: "Mathematics",
    activity: "Playing Soccer",
    circumstances:
      "Yoseph is a bright boy who lives with his mother and a sibling in an impoverished neighborhood of Addis Ababa. Sadly, his parents are separated and although Yoseph's mother work hard as a daily laborer, her inconsistent earnings are not enough to meet the family's needs and she cannot afford to pay his school fees. Without support, Yoseph's education is at risk.",
    food: "Meat",
    grade: 2 ,
    profession: "Doctor",
  },
  {
    id: 24,
    name: "Zablon Habtamu",
    img: "https://cdn.givecloud.co/s/files/2/0000/0908/sponsorships/zablon-habtmu-2_300x_cropped_center.jpg",
    age: 6,
    country: "Ethiopia",
    subject: "Amharic (Local Language)",
    activity: "Playing Soccer",
    circumstances:
      "Zablon is a bright little boy who lives with his parents and three siblings in a vulnerable community of Addis Ababa. Sadly, his father is physically disabled and cannot find a job. Although Zablon's mother works hard as a daily laborer, her earnings are not enough to meet the family's needs and she cannot afford to pay his school fees. Without support, Zablon's education is at risk.",
    food: "Macaroni",
    grade: "Kindergarten",
    profession: "Policeman",
  },
  {
    id: 25,
    name: "Zablon Habtamu",
    img: "https://cdn.givecloud.co/s/files/2/0000/0908/sponsorships/zablon-habtmu-2_300x_cropped_center.jpg",
    age: 6,
    country: "Ethiopia",
    subject: "Amharic (Local Language)",
    activity: "Playing Soccer",
    circumstances:
      "Zablon is a bright little boy who lives with his parents and three siblings in a vulnerable community of Addis Ababa. Sadly, his father is physically disabled and cannot find a job. Although Zablon's mother works hard as a daily laborer, her earnings are not enough to meet the family's needs and she cannot afford to pay his school fees. Without support, Zablon's education is at risk.",
    food: "Macaroni",
    grade: "Kindergarten",
    profession: "Policeman",
  },
  {
    id: 26,
    name: "Beimnet Hailemariam",
    img: "https://cdn.givecloud.co/s/files/2/0000/0908/sponsorships/microsoftteams-image-23_300x_cropped_center.png",
    age: 8,
    country: "Ethiopia",
    subject: "Mathematics",
    activity: "Playing Soccer",
    circumstances:
      "Beimnet is a bright boy who lives with his mother in a vulnerable community of Addis Ababa. Sadly, his father has passed away and his mother has a medical condition. Beimnet's mother's income is inconsistent even though she works hard as a daily laborer. Her earnings are not enough to meet their needs and she cannot afford to pay his school fees. Without support, Beimnet's education is at risk.",
    food: "Rice",
    grade: 2 ,
    profession: "Pilot",
  },
  {
    id: 27,
    name: "Amen Abas",
    img: "https://cdn.givecloud.co/s/files/2/0000/0908/sponsorships/microsoftteams-image-21_300x_cropped_center.png",
    age: 6,
    country: "Ethiopia",
    subject: "Too early to decide",
    activity: "Playing Soccer",
    circumstances:
      "Amen is a sweet little boy who lives with his grandmother in an impoverished neighborhood of Addis Ababa. Sadly, his mother has passed away and his father does not support him. Amen's grandmother's income is inconsistent even though she works hard as a daily laborer. Her earnings are not enough to meet their needs and she cannot afford to pay his school fees. Without support, Amen's education is at risk.",
    food: "Rice",
    grade: "Kindergarten" ,
    profession: "Doctor",
  },
  {
    id: 28,
    name: "Nuru Jemal",
    img: "https://cdn.givecloud.co/s/files/2/0000/0908/sponsorships/nuru-jemal-3_300x_cropped_center.jpg",
    age: 8,
    country: "Ethiopia",
    subject: "Mathematics",
    activity: "Puzzle",
    circumstances:
      "Nuru is a bright little boy who lives with his mother and two siblings in an impoverished neighborhood of Addis Ababa. Sadly, his father has abandoned the family and although Nuru's mother works hard as a daily laborer, her earnings are not enough to meet the family's needs and she cannot afford to pay his school fees. Without support, Nuru's education is at risk.",
    food: "Watermelon",
    grade: 2 ,
    profession: "Pilot",
  },
  {
    id: 29,
    name: "Mohammed Nuriye",
    img: "https://cdn.givecloud.co/s/files/2/0000/0908/sponsorships/microsoftteams-image-28_300x_cropped_center.png",
    age: 5,
    country: "Ethiopia",
    subject: "Drawing",
    activity: "Playing Soccer",
    circumstances:
      "Mohammed is a sweet little boy who lives with his mother in a vulnerable community of Addis Ababa. Although Mohammed's mother works hard as street vendor, her earnings are not enough to meet their needs and she cannot afford to pay his school fees. Without support, Mohammed's education is at risk.",
    food: "Fifir (Traditional Food)",
    grade: "Kindergarten" ,
    profession: "Soccer Player",
  },
  {
    id: 30,
    name: "Miskaleb Mihretab",
    img: "https://cdn.givecloud.co/s/files/2/0000/0908/sponsorships/microsoftteams-image-20-1_300x_cropped_center.png",
    age: 5,
    country: "Ethiopia",
    subject: "Drawing",
    activity: "Playing Soccer",
    circumstances:
      "Miskaleb is a sweet little boy who lives with his grandmother in an impoverished neighborhood of Addis Ababa. Sadly, his father has passed away and his mother is unemployed and cannot support him. Miskaleb's grandmother's income is inconsistent even though she works hard as a daily laborer. Her earnings are not enough to meet their needs and she cannot afford to pay his school fees. Without support, Miskaleb's education is at risk.",
    food: "Fifir (Traditional Food)",
    grade: "Kindergarten" ,
    profession: "Doctor",
  },
  {
    id: 31,
    name: "Samuel Kasse",
    img: "https://cdn.givecloud.co/s/files/2/0000/0908/sponsorships/microsoftteams-image-37_300x_cropped_center.png",
    age: 12,
    country: "Ethiopia",
    subject: "English",
    activity: "Scientist",
    circumstances:
      "Samuel is a bright boy who lives with his mother and three siblings in an impoverished neighborhood of Addis Ababa. Sadly, Samuel's parents have separated, and he is raised by a single mother. Samuel's mother income is inconsistent even though she works hard as a daily laborer. Her earnings are not enough to meet the family's needs and she cannot afford to pay Samuel's school fees. Without support, Samuel's education is at risk.",
    food: "Shiro (Traditional Food)",
    grade: 4 ,
    profession: "Soccer Player",
  }






];
